"""The BRD requirement inventory, as data.

Generated from docs/00-requirements/02-module-inventory.md, which is the
approved inventory of the 238 functional requirements in
source/KIYA360_BRD.pdf v2.0. It is copied into the app because the app runs
from a bench and cannot read the docs tree at runtime.

Do not hand-edit. Regenerate it from the inventory when that document changes;
the generator is scripts/generate_brd_requirements.py at the repository root.

The app cannot verify this file against the inventory at runtime, because the
bench has the app mounted without the docs tree. What the structural tests do
check is that the shape is still sound -- 238 requirements, 28 modules, unique
and well-formed ids -- so a truncated or corrupted regeneration is caught even
though a stale one is not.

Every requirement in the BRD is recorded with its detail as
"TBD -- The BRD does not specify this detail." That is a fact about the BRD,
not an omission here, and it is why coverage is reported as what the system
models rather than as requirements "met".
"""

#: module number -> module name. 28 modules.
MODULES = {
	1: 'Platform & Administration',
	2: 'CRM',
	3: 'Sales',
	4: 'Marketing',
	5: 'Customer Service',
	6: 'Procurement',
	7: 'Supplier Management',
	8: 'Inventory',
	9: 'Warehouse',
	10: 'Manufacturing',
	11: 'MRP & Planning',
	12: 'Quality',
	13: 'Asset Management',
	14: 'Maintenance & Field Service',
	15: 'Logistics & Transportation',
	16: 'Projects',
	17: 'Finance & Accounting',
	18: 'Tax & Statutory Compliance',
	19: 'HR & Payroll',
	20: 'E-Commerce',
	21: 'Document Management',
	22: 'Business Intelligence',
	23: 'EPM / Budget / Forecast',
	24: 'Workflow & Approvals',
	25: 'AI & Automation',
	26: 'Integration & API',
	27: 'Mobile Application',
	28: 'Audit, Security & Compliance',
}

#: (requirement id, name, module number, classification). 238 rows.
REQUIREMENTS = [
	('FR-PADM-1.1.1', 'Company Master', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.1.2', 'Branch Master', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.1.3', 'Business Unit', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.1.4', 'Department', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.1.5', 'Division', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.1.6', 'Location', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.2.1', 'User Management', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.2.2', 'Role Management', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.2.3', 'Permission Management', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.2.4', 'Approval Authority', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.2.5', 'User Groups', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.2.6', 'Session Management', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.3.1', 'Login & Authentication', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.3.2', 'IP Restrictions', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.3.3', 'Device Management', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.3.4', 'Data Encryption', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.3.5', 'Session Security', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.3.6', 'Access Control', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.4.1', 'Customer Master', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.4.2', 'Supplier Master', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.4.3', 'Item Master', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.4.4', 'Employee Master', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.4.5', 'Tax Master', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.4.6', 'Currency Master', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.4.7', 'UOM Master', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.5.1', 'System Settings', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.5.2', 'Financial Settings', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.5.3', 'Sales Settings', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.5.4', 'Purchase Settings', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.5.5', 'Inventory Settings', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.5.6', 'Manufacturing Settings', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.5.7', 'Service Settings', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.6.1', 'Document Series', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.6.2', 'Transaction Series', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.6.3', 'Master Series', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.6.4', 'Project Series', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.6.5', 'Service Series', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.6.6', 'Asset Series', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.7.1', 'Email Notifications', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.7.2', 'WhatsApp Notifications', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.7.3', 'SMS Notifications', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.7.4', 'Push Notifications', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.7.5', 'In-App Notifications', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.7.6', 'Notification Templates', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.8.1', 'Login Log', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.8.2', 'Data Change Log', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.8.3', 'Transaction Log', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.8.4', 'Approval Log', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.8.5', 'API Log', 1, 'BRD-REQUIRED'),
	('FR-PADM-1.8.6', 'Report Log', 1, 'BRD-REQUIRED'),
	('FR-CRM-001', 'Leads', 2, 'BRD-REQUIRED'),
	('FR-CRM-002', 'Opportunities', 2, 'BRD-REQUIRED'),
	('FR-CRM-003', 'Accounts', 2, 'BRD-REQUIRED'),
	('FR-CRM-004', 'Contacts', 2, 'BRD-REQUIRED'),
	('FR-CRM-005', 'Activities', 2, 'BRD-REQUIRED'),
	('FR-CRM-006', 'Pipeline Management', 2, 'BRD-REQUIRED'),
	('FR-CRM-007', 'Campaigns', 2, 'BRD-REQUIRED'),
	('FR-CRM-008', 'Customer 360 View', 2, 'BRD-REQUIRED'),
	('FR-SALES-001', 'Enquiries', 3, 'BRD-REQUIRED'),
	('FR-SALES-002', 'Quotations', 3, 'BRD-REQUIRED'),
	('FR-SALES-003', 'Sales Orders', 3, 'BRD-REQUIRED'),
	('FR-SALES-004', 'Pricing & Discounts', 3, 'BRD-REQUIRED'),
	('FR-SALES-005', 'Delivery & Dispatch', 3, 'BRD-REQUIRED'),
	('FR-SALES-006', 'Returns', 3, 'BRD-REQUIRED'),
	('FR-SALES-007', 'Credit Memos', 3, 'BRD-REQUIRED'),
	('FR-SALES-008', 'Sales Analytics', 3, 'BRD-REQUIRED'),
	('FR-MKT-001', 'Campaigns', 4, 'BRD-REQUIRED'),
	('FR-MKT-002', 'Email Marketing', 4, 'BRD-REQUIRED'),
	('FR-MKT-003', 'Digital Marketing', 4, 'BRD-REQUIRED'),
	('FR-MKT-004', 'Events & Webinars', 4, 'BRD-REQUIRED'),
	('FR-MKT-005', 'Lead Generation', 4, 'BRD-REQUIRED'),
	('FR-MKT-006', 'Market Analysis', 4, 'BRD-REQUIRED'),
	('FR-MKT-007', 'Marketing Analytics', 4, 'BRD-REQUIRED'),
	('FR-CSVC-001', 'Case Management', 5, 'BRD-REQUIRED'),
	('FR-CSVC-002', 'Service Tickets', 5, 'BRD-REQUIRED'),
	('FR-CSVC-003', 'Knowledge Base', 5, 'BRD-REQUIRED'),
	('FR-CSVC-004', 'SLA Management', 5, 'BRD-REQUIRED'),
	('FR-CSVC-005', 'Customer Feedback', 5, 'BRD-REQUIRED'),
	('FR-CSVC-006', 'Escalations', 5, 'BRD-REQUIRED'),
	('FR-CSVC-007', 'Service Analytics', 5, 'BRD-REQUIRED'),
	('FR-PROC-001', 'Purchase Requisition', 6, 'BRD-REQUIRED'),
	('FR-PROC-002', 'RFQ / RFP', 6, 'BRD-REQUIRED'),
	('FR-PROC-003', 'Supplier Quotations', 6, 'BRD-REQUIRED'),
	('FR-PROC-004', 'Purchase Orders', 6, 'BRD-REQUIRED'),
	('FR-PROC-005', 'Goods Receipt', 6, 'BRD-REQUIRED'),
	('FR-PROC-006', 'Returns', 6, 'BRD-REQUIRED'),
	('FR-PROC-007', 'Procurement Analytics', 6, 'BRD-REQUIRED'),
	('FR-SUPM-001', 'Supplier Master', 7, 'BRD-REQUIRED'),
	('FR-SUPM-002', 'Supplier Classification', 7, 'BRD-REQUIRED'),
	('FR-SUPM-003', 'Supplier Evaluation', 7, 'BRD-REQUIRED'),
	('FR-SUPM-004', 'Contracts', 7, 'BRD-REQUIRED'),
	('FR-SUPM-005', 'Performance Scorecard', 7, 'BRD-REQUIRED'),
	('FR-SUPM-006', 'Supplier Portal', 7, 'BRD-REQUIRED'),
	('FR-INV-001', 'Item Master', 8, 'BRD-REQUIRED'),
	('FR-INV-002', 'Stock Quantity', 8, 'BRD-REQUIRED'),
	('FR-INV-003', 'Batch / Serial Tracking', 8, 'BRD-REQUIRED'),
	('FR-INV-004', 'Stock Transfers', 8, 'BRD-REQUIRED'),
	('FR-INV-005', 'Cycle Counting', 8, 'BRD-REQUIRED'),
	('FR-INV-006', 'Stock Valuation', 8, 'BRD-REQUIRED'),
	('FR-INV-007', 'Inventory Analytics', 8, 'BRD-REQUIRED'),
	('FR-WH-001', 'Warehouse Setup', 9, 'BRD-REQUIRED'),
	('FR-WH-002', 'Bin Locations', 9, 'BRD-REQUIRED'),
	('FR-WH-003', 'Inbound Management', 9, 'BRD-REQUIRED'),
	('FR-WH-004', 'Outbound Management', 9, 'BRD-REQUIRED'),
	('FR-WH-005', 'Picking & Packing', 9, 'BRD-REQUIRED'),
	('FR-WH-006', 'Warehouse Transfers', 9, 'BRD-REQUIRED'),
	('FR-WH-007', 'WMS Analytics', 9, 'BRD-REQUIRED'),
	('FR-MFG-001', 'BOM Management', 10, 'BRD-REQUIRED'),
	('FR-MFG-002', 'Routing', 10, 'BRD-REQUIRED'),
	('FR-MFG-003', 'Work Orders', 10, 'BRD-REQUIRED'),
	('FR-MFG-004', 'Production Planning', 10, 'BRD-REQUIRED'),
	('FR-MFG-005', 'Shop Floor Execution', 10, 'BRD-REQUIRED'),
	('FR-MFG-006', 'Costing', 10, 'BRD-REQUIRED'),
	('FR-MFG-007', 'By-Products / Co-products', 10, 'BRD-REQUIRED'),
	('FR-MRP-001', 'Demand Planning', 11, 'BRD-REQUIRED'),
	('FR-MRP-002', 'Material Requirements', 11, 'BRD-REQUIRED'),
	('FR-MRP-003', 'Capacity Planning', 11, 'BRD-REQUIRED'),
	('FR-MRP-004', 'Production Planning', 11, 'BRD-REQUIRED'),
	('FR-MRP-005', 'Supply Planning', 11, 'BRD-REQUIRED'),
	('FR-MRP-006', 'Schedule Planning', 11, 'BRD-REQUIRED'),
	('FR-MRP-007', 'MRP Analytics', 11, 'BRD-REQUIRED'),
	('FR-QLTY-001', 'Quality Planning', 12, 'BRD-REQUIRED'),
	('FR-QLTY-002', 'Incoming Inspection', 12, 'BRD-REQUIRED'),
	('FR-QLTY-003', 'In-Process Inspection', 12, 'BRD-REQUIRED'),
	('FR-QLTY-004', 'Final Inspection', 12, 'BRD-REQUIRED'),
	('FR-QLTY-005', 'Quality Control', 12, 'BRD-REQUIRED'),
	('FR-QLTY-006', 'NCR / CAPA', 12, 'BRD-REQUIRED'),
	('FR-QLTY-007', 'Quality Analytics', 12, 'BRD-REQUIRED'),
	('FR-AST-001', 'Asset Master', 13, 'BRD-REQUIRED'),
	('FR-AST-002', 'Asset Classification', 13, 'BRD-REQUIRED'),
	('FR-AST-003', 'Asset Tracking', 13, 'BRD-REQUIRED'),
	('FR-AST-004', 'Asset Depreciation', 13, 'BRD-REQUIRED'),
	('FR-AST-005', 'Asset Valuation', 13, 'BRD-REQUIRED'),
	('FR-AST-006', 'Asset Lifecycle', 13, 'BRD-REQUIRED'),
	('FR-AST-007', 'Asset Analytics', 13, 'BRD-REQUIRED'),
	('FR-MFS-001', 'Maintenance Planning', 14, 'BRD-REQUIRED'),
	('FR-MFS-002', 'Work Orders', 14, 'BRD-REQUIRED'),
	('FR-MFS-003', 'Preventive Maintenance', 14, 'BRD-REQUIRED'),
	('FR-MFS-004', 'Breakdown Maintenance', 14, 'BRD-REQUIRED'),
	('FR-MFS-005', 'Spare Parts Management', 14, 'BRD-REQUIRED'),
	('FR-MFS-006', 'Service Contracts', 14, 'BRD-REQUIRED'),
	('FR-MFS-007', 'Field Service', 14, 'BRD-REQUIRED'),
	('FR-LOG-001', 'Logistics Planning', 15, 'BRD-REQUIRED'),
	('FR-LOG-002', 'Freight Management', 15, 'BRD-REQUIRED'),
	('FR-LOG-003', 'Shipment Management', 15, 'BRD-REQUIRED'),
	('FR-LOG-004', 'Carrier Management', 15, 'BRD-REQUIRED'),
	('FR-LOG-005', 'Tracking & Tracing', 15, 'BRD-REQUIRED'),
	('FR-LOG-006', 'Delivery Confirmation', 15, 'BRD-REQUIRED'),
	('FR-LOG-007', 'Logistics Analytics', 15, 'BRD-REQUIRED'),
	('FR-PROJ-001', 'Project Planning', 16, 'BRD-REQUIRED'),
	('FR-PROJ-002', 'Project Budgeting', 16, 'BRD-REQUIRED'),
	('FR-PROJ-003', 'Project Execution', 16, 'BRD-REQUIRED'),
	('FR-PROJ-004', 'Resource Planning', 16, 'BRD-REQUIRED'),
	('FR-PROJ-005', 'Time & Expense', 16, 'BRD-REQUIRED'),
	('FR-PROJ-006', 'Project Billing', 16, 'BRD-REQUIRED'),
	('FR-PROJ-007', 'Project Analytics', 16, 'BRD-REQUIRED'),
	('FR-FIN-001', 'General Ledger', 17, 'BRD-REQUIRED'),
	('FR-FIN-002', 'Accounts Payable', 17, 'BRD-REQUIRED'),
	('FR-FIN-003', 'Accounts Receivable', 17, 'BRD-REQUIRED'),
	('FR-FIN-004', 'Cash & Bank', 17, 'BRD-REQUIRED'),
	('FR-FIN-005', 'Fixed Assets', 17, 'BRD-REQUIRED'),
	('FR-FIN-006', 'Cost Accounting', 17, 'BRD-REQUIRED'),
	('FR-FIN-007', 'Financial Reporting', 17, 'BRD-REQUIRED'),
	('FR-TAX-001', 'Global Tax Engine', 18, 'BRD-REQUIRED'),
	('FR-TAX-002', 'Country Tax Rules', 18, 'BRD-REQUIRED'),
	('FR-TAX-003', 'GST / VAT / Sales Tax', 18, 'BRD-REQUIRED'),
	('FR-TAX-004', 'Withholding Tax', 18, 'BRD-REQUIRED'),
	('FR-TAX-005', 'E-Invoicing / E-Way Bill', 18, 'BRD-REQUIRED'),
	('FR-TAX-006', 'Tax Returns', 18, 'BRD-REQUIRED'),
	('FR-TAX-007', 'Statutory Reports', 18, 'BRD-REQUIRED'),
	('FR-HR-001', 'Employee Master', 19, 'BRD-REQUIRED'),
	('FR-HR-002', 'Organization Management', 19, 'BRD-REQUIRED'),
	('FR-HR-003', 'Attendance & Leave', 19, 'BRD-REQUIRED'),
	('FR-HR-004', 'Payroll Processing', 19, 'BRD-REQUIRED'),
	('FR-HR-005', 'Benefits Management', 19, 'BRD-REQUIRED'),
	('FR-HR-006', 'Performance Management', 19, 'BRD-REQUIRED'),
	('FR-HR-007', 'HR Analytics', 19, 'BRD-REQUIRED'),
	('FR-ECOM-001', 'Online Store', 20, 'BRD-REQUIRED'),
	('FR-ECOM-002', 'Product Catalog', 20, 'BRD-REQUIRED'),
	('FR-ECOM-003', 'Shopping Cart', 20, 'BRD-REQUIRED'),
	('FR-ECOM-004', 'Order Management', 20, 'BRD-REQUIRED'),
	('FR-ECOM-005', 'Payment Gateway', 20, 'BRD-REQUIRED'),
	('FR-ECOM-006', 'Promotions', 20, 'BRD-REQUIRED'),
	('FR-ECOM-007', 'Customer Portal', 20, 'BRD-REQUIRED'),
	('FR-DOCM-001', 'Document Capture', 21, 'BRD-REQUIRED'),
	('FR-DOCM-002', 'Document Storage', 21, 'BRD-REQUIRED'),
	('FR-DOCM-003', 'Version Control', 21, 'BRD-REQUIRED'),
	('FR-DOCM-004', 'Document Sharing', 21, 'BRD-REQUIRED'),
	('FR-DOCM-005', 'Access Control', 21, 'BRD-REQUIRED'),
	('FR-DOCM-006', 'Document Workflow', 21, 'BRD-REQUIRED'),
	('FR-DOCM-007', 'Digital Signatures', 21, 'BRD-REQUIRED'),
	('FR-BI-001', 'Dashboards', 22, 'BRD-REQUIRED'),
	('FR-BI-002', 'Reports', 22, 'BRD-REQUIRED'),
	('FR-BI-003', 'KPI Management', 22, 'BRD-REQUIRED'),
	('FR-BI-004', 'Data Visualization', 22, 'BRD-REQUIRED'),
	('FR-BI-005', 'Ad-hoc Analysis', 22, 'BRD-REQUIRED'),
	('FR-BI-006', 'Predictive Analytics', 22, 'BRD-REQUIRED'),
	('FR-BI-007', 'BI Mobile App', 22, 'BRD-REQUIRED'),
	('FR-EPM-001', 'Budgeting', 23, 'BRD-REQUIRED'),
	('FR-EPM-002', 'Forecasting', 23, 'BRD-REQUIRED'),
	('FR-EPM-003', 'Financial Planning', 23, 'BRD-REQUIRED'),
	('FR-EPM-004', 'Scenario Planning', 23, 'BRD-REQUIRED'),
	('FR-EPM-005', 'Consolidation', 23, 'BRD-REQUIRED'),
	('FR-EPM-006', 'Variance Analysis', 23, 'BRD-REQUIRED'),
	('FR-EPM-007', 'EPM Analytics', 23, 'BRD-REQUIRED'),
	('FR-WFA-001', 'Workflow Builder', 24, 'BRD-REQUIRED'),
	('FR-WFA-002', 'Approval Matrix', 24, 'BRD-REQUIRED'),
	('FR-WFA-003', 'Escalation Rules', 24, 'BRD-REQUIRED'),
	('FR-WFA-004', 'Delegation', 24, 'BRD-REQUIRED'),
	('FR-WFA-005', 'Notifications', 24, 'BRD-REQUIRED'),
	('FR-WFA-006', 'Audit Trail', 24, 'BRD-REQUIRED'),
	('FR-WFA-007', 'Mobile Approvals', 24, 'BRD-REQUIRED'),
	('FR-AIAU-001', 'AI Insights', 25, 'BRD-REQUIRED'),
	('FR-AIAU-002', 'Predictive Analytics', 25, 'BRD-REQUIRED'),
	('FR-AIAU-003', 'Process Automation', 25, 'BRD-REQUIRED'),
	('FR-AIAU-004', 'RPA Bots', 25, 'BRD-REQUIRED'),
	('FR-AIAU-005', 'AI Chat Assistant', 25, 'BRD-REQUIRED'),
	('FR-AIAU-006', 'Anomaly Detection', 25, 'BRD-REQUIRED'),
	('FR-AIAU-007', 'Machine Learning', 25, 'BRD-REQUIRED'),
	('FR-INTG-001', 'API Management', 26, 'BRD-REQUIRED'),
	('FR-INTG-002', 'System Integration', 26, 'BRD-REQUIRED'),
	('FR-INTG-003', 'Data Sync', 26, 'BRD-REQUIRED'),
	('FR-INTG-004', 'Webhooks', 26, 'BRD-REQUIRED'),
	('FR-INTG-005', 'Third Party Apps', 26, 'BRD-REQUIRED'),
	('FR-INTG-006', 'Middleware', 26, 'BRD-REQUIRED'),
	('FR-INTG-007', 'Integration Monitoring', 26, 'BRD-REQUIRED'),
	('FR-MOB-001', 'Sales App', 27, 'BRD-REQUIRED'),
	('FR-MOB-002', 'Service App', 27, 'BRD-REQUIRED'),
	('FR-MOB-003', 'Dashboard App', 27, 'BRD-REQUIRED'),
	('FR-MOB-004', 'Offline Sync App', 27, 'BRD-REQUIRED'),
	('FR-MOB-005', 'Inventory App', 27, 'BRD-REQUIRED'),
	('FR-MOB-006', 'Push Notifications', 27, 'BRD-REQUIRED'),
	('FR-MOB-007', 'Approvals App', 27, 'BRD-REQUIRED'),
	('FR-ASC-001', 'Policy Management', 28, 'BRD-REQUIRED'),
	('FR-ASC-002', 'Access Control', 28, 'BRD-REQUIRED'),
	('FR-ASC-003', 'Data Security', 28, 'BRD-REQUIRED'),
	('FR-ASC-004', 'Risk Management', 28, 'BRD-REQUIRED'),
	('FR-ASC-005', 'Security Monitoring', 28, 'BRD-REQUIRED'),
]
